#+title: README
#+author: Pohlrabi

* Table of Content :toc:
- [[#overview][Overview]]
- [[#features][Features]]
- [[#installation][Installation]]
  - [[#manually][Manually]]
  - [[#using-elpaca][Using elpaca]]
- [[#usage][Usage]]
- [[#configuration][Configuration]]

* Overview
psiman (Pohl's Simple Index Manager) is an Emacs package designed to manage system packages using a declarative approach.
It allows you to define a list of packages in a file and synchronizes the system packages with this list by installing missing packages and uninstalling packages that are no longer in the list.

* Features
- Declarative Package Management: Define your desired package list in a file.
- Automatic Installation and Uninstallation: Synchronize your system packages with the declared list.
- Can also do the same with other type of commands like symlink or enabling/disabling services

* Installation
** Manually
1. Clone the repo
#+begin_src sh
git clone https://github.com/pohlrabi404/psiman.git
#+end_src
2. Load the package
Add the following to your Emacs configuration file
#+begin_src elisp
(add-to-list 'load-path "path/to/your/psiman/installation/dir")
(require 'psiman)
#+end_src

** TODO Using elpaca

* Usage
1. Define package list
Create a file at the path specified in *psiman-cmd-list*. Each line in this file should be name of a package. For example:
#+begin_src text
vim
neovim
zsh
#+end_src

2. Sync packages
Run the following command to sync the packages compared to cache file
#+begin_src elisp
M-x psiman-sync
#+end_src

* Configuration
You can add commands like below
- Example:
#+begin_src elisp
(setq psiman-cmd-list
      '(("paru -S --noconfirm %s"
         "paru -R --noconfirm %s"
         "~/.dotfiles/.pkg-path"
         "~/.config/.pkg-cache"
         " ")

        ("pacman -S --noconfirm %s"
         "pacman -S --noconfirm %s"
         "~/.dotfiles/.pacman-path"
         "~/.config/pacman-cache"
         " ")))
#+end_src
